import sqlite3
conn = sqlite3.connect("data/ais_employee.db")
c = conn.cursor()
c.execute("UPDATE tasks SET status = 'TODO', completed_at = NULL WHERE id = 16")
c.execute("UPDATE projects SET status = 'PLANNING', progress = 0 WHERE id = 5")
conn.commit()
c.execute("SELECT id, title, status FROM tasks WHERE id = 16")
print("Task 16:", c.fetchone())
c.execute("SELECT id, project_name, status, progress FROM projects WHERE id = 5")
print("Project 5:", c.fetchone())
conn.close()
print("Reset complete.")
